name: Django Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: SSH into EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: ${{ secrets.EC2_SSH_PORT }}
    - name: Copy project files to EC2 instance
      uses: appleboy/scp-action@master
      with:
        source: ./
        target: /home/ubuntu/project
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: ${{ secrets.EC2_SSH_PORT }}
    - name: Install dependencies on EC2 instance
      run: |
        ssh ubuntu@${{ secrets.EC2_HOST }} -p ${{ secrets.EC2_SSH_PORT }} 'cd /home/ubuntu/project && python -m pip install --upgrade pip && pip install -r requirements.txt'
